program gdc;

{.$DEFINE VIRTUALUI}

uses
  nxReplacementMemoryManager,
  nxReplacementMove,
  nxsdServerEngine,
  Windows,
  Forms,
  cxLookAndFeels,
  WebBrowser in '..\..\Lib\WebBrowser.pas' {WebForm},
  PrintSystem in '..\..\Lib\PrintSystem.pas' {PrintSystemDataModule: TDataModule},
  f_prg in '..\..\Lib\f_prg.pas' {ProcessFrame: TFrame},
  EditableGrid in '..\..\Lib\EditableGrid.pas' {EditableGridFrame: TFrame},
  EnterpriseDataAccess in '..\..\Lib\EnterpriseDataAccess.pas' {EnterpriseDataModule: TDataModule},
  p_gph in '..\Gdm00\p_gph.pas' {GphTemplateForm: TgForm},
  b_sdd in '..\Gdm00\b_sdd.pas' {boxSddForm},
  Gdm10Frm in '..\Gdm10\Gdm10Frm.pas' {Gds10Frm: TFrame},
  Gdm70Frm in '..\Gdm70\Gdm70Frm.pas' {Gds70Frm: TFrame},
  gdm40Dm in '..\Gdm40\gdm40Dm.pas' {DataModule40: TDataModule},
  gdm60Frm in '..\Gdm60\gdm60Frm.pas' {Gds60Frm: TFrame},
  f_app in '..\Gdm19\f_app.pas' {ApplicationFrame: TFrame},
  Gdm60Dm in '..\Gdm60\Gdm60Dm.pas' {DataModule60: TDataModule},
  gdm200Dm in '..\Gdm200\gdm200Dm.pas' {DataModule200: TDataModule},
  b_eap in '..\Gdm40\b_eap.pas' {BrwEapForm},
  f_cpe40 in '..\Gdm40\f_cpe40.pas' {RptCpe40Frame: TDataModule},
  f_cnf201 in '..\Gdm201\f_cnf201.pas' {TrazabilidadModule: TDataModule},
  f_cnf202 in '..\Gdm202\f_cnf202.pas' {PartidasPresupuestariasModule: TDataModule},
  f_cnf203 in '..\Gdm203\f_cnf203.pas' {EnvasesModule: TDataModule},
  f_cnf204 in '..\Gdm204\f_cnf204.pas' {ExportacionModule: TDataModule},
  gdm203Dm in '..\Gdm203\gdm203Dm.pas' {DataModule203: TDataModule},
  gdm204Dm in '..\Gdm204\gdm204Dm.pas' {DataModule204: TDataModule},
  dm_sen in '..\Gdm203\dm_sen.pas' {StockEnvasesModule: TDataModule},
  i_pck in '..\Gdm204\i_pck.pas' {FrmPckForm},
  cm_mve40 in '..\Gdm40\cm_mve40.pas' {MntMve40Module: TDataModule},
  cx_emp in '..\Gdm00\cx_emp.pas' {CxEmpForm: TgForm},
  a_cli in '..\Gdm10\a_cli.pas' {MntCliForm: TgForm},
  a_pro in '..\Gdm10\a_pro.pas' {mntProForm: TgForm},
  Gim00Fields in '..\..\Interface\Gim00\Gim00Fields.pas',
  Gim10Fields in '..\..\Interface\Gim10\Gim10Fields.pas',
  Gim30Fields in '..\..\Interface\Gim30\Gim30Fields.pas',
  dmi_sal in '..\..\Interface\Gim10\dmi_sal.pas',
  Gim40Fields in '..\..\Interface\Gim40\Gim40Fields.pas',
  AppManager in '..\..\Lib\AppManager.pas',
  dmi_ast in '..\..\Interface\Gim10\dmi_ast.pas',
  dmi_ecc in '..\..\Interface\Gim10\dmi_ecc.pas',
  ApunteIntf in '..\..\Interface\Gim10\ApunteIntf.pas',
  AsientoIntf in '..\..\Interface\Gim10\AsientoIntf.pas',
  EfectoCobrarIntf in '..\..\Interface\Gim10\EfectoCobrarIntf.pas',
  dmi_ecp in '..\..\Interface\Gim10\dmi_ecp.pas',
  EfectoPagarIntf in '..\..\Interface\Gim10\EfectoPagarIntf.pas',
  dmi_rdp in '..\..\Interface\Gim10\dmi_rdp.pas',
  RemesaPagoIntf in '..\..\Interface\Gim10\RemesaPagoIntf.pas',
  dmi_rem in '..\..\Interface\Gim10\dmi_rem.pas',
  RemesaIntf in '..\..\Interface\Gim10\RemesaIntf.pas',
  dm_ecc in '..\Gdm10\dm_ecc.pas' {EfectoCobrarModule: TDataModule},
  SessionIntf in '..\..\Interface\Lib\SessionIntf.pas',
  dm_ccf in '..\Gdm70\dm_ccf.pas' {CierreCicloFabricacionModule: TDataModule},
  dmi_ccn in '..\..\Interface\Gim10\dmi_ccn.pas',
  dmi_rda in '..\..\Interface\Gim10\dmi_rda.pas',
  dmi_vec in '..\..\Interface\Gim10\dmi_vec.pas',
  dmi_gaa in '..\..\Interface\Gim10\dmi_gaa.pas',
  dmi_sds in '..\..\Interface\Gim10\dmi_sds.pas',
  dmi_cde in '..\..\Interface\Gim10\dmi_cde.pas',
  dm_fac in '..\Gdm10\dm_fac.pas' {FacturaModule},
  dm_ast in '..\Gdm10\dm_ast.pas' {AsientoModule: TDataModule},
  dmi_fac in '..\..\Interface\Gim10\dmi_fac.pas',
  LineaMovimientoIntf in '..\..\Interface\Gim30\LineaMovimientoIntf.pas',
  dmi_mov in '..\..\Interface\Gim30\dmi_mov.pas',
  MovimientoIntf in '..\..\Interface\Gim30\MovimientoIntf.pas',
  SessionDataAccess in '..\..\Lib\SessionDataAccess.pas' {SessionDataModule: TDataModule},
  EditSelector in '..\..\Lib\EditSelector.pas' {SelectorRelationForm},
  dmi_fdc in '..\..\Interface\Gim30\dmi_fdc.pas',
  dmi_rdr in '..\..\Interface\Gim30\dmi_rdr.pas',
  ParametrosFacturacionIntf in '..\..\Interface\Gim30\ParametrosFacturacionIntf.pas',
  dmi_fdv in '..\..\Interface\Gim30\dmi_fdv.pas',
  dm_ecp in '..\Gdm10\dm_ecp.pas' {EfectoPagarModule: TDataModule},
  dm_rem in '..\Gdm10\dm_rem.pas' {RemesaModule: TDataModule},
  dm_rdp in '..\Gdm10\dm_rdp.pas' {RemesaPagoModule: TDataModule},
  dmi_sto in '..\..\Interface\Gim30\dmi_sto.pas',
  dmi_ric in '..\..\Interface\Gim10\dmi_ric.pas',
  FacturaVentasIntf in '..\..\Interface\Gim30\FacturaVentasIntf.pas',
  dmi_vpe in '..\..\Interface\Gim30\dmi_vpe.pas',
  Gim90Fields in '..\..\Interface\Gim90\Gim90Fields.pas',
  a_cat in '..\Gdm207\a_cat.pas' {MntCatForm: TgForm},
  cx_cat in '..\Gdm207\cx_cat.pas' {CxCatForm: TgForm},
  dm_rea207 in '..\Gdm207\dm_rea207.pas' {RegistroActualizacionTiendaModule: TDataModule},
  gdm207Dm in '..\Gdm207\gdm207Dm.pas' {DataModule207: TDataModule},
  l_cat in '..\Gdm207\l_cat.pas' {RptCatForm: TgForm},
  a_pde207 in '..\Gdm207\a_pde207.pas' {MntPde207Form: TgForm},
  f_cnf207 in '..\Gdm207\f_cnf207.pas' {Configuracion207Module: TDataModule},
  Gim207Fields in '..\..\Interface\Gim207\Gim207Fields.pas',
  dm_cat in '..\Gdm207\dm_cat.pas' {CategoriaModule: TDataModule},
  dmi_sdt in '..\..\Interface\Gim207\dmi_sdt.pas',
  dmi_lma in '..\..\Interface\Gim30\dmi_lma.pas',
  dmi_cec in '..\..\Interface\Gim30\dmi_cec.pas',
  dmi_iav101 in '..\..\Interface\Gim101\dmi_iav101.pas',
  Gim101Fields in '..\..\Interface\Gim101\Gim101Fields.pas',
  Gim203Fields in '..\..\Interface\Gim203\Gim203Fields.pas',
  Gim204Fields in '..\..\Interface\Gim204\Gim204Fields.pas',
  dmi_iav103 in '..\..\Interface\Gim103\dmi_iav103.pas',
  Gim103Fields in '..\..\Interface\Gim103\Gim103Fields.pas',
  dmi_hdc in '..\..\Interface\Gim40\dmi_hdc.pas',
  HojaCargaIntf in '..\..\Interface\Gim40\HojaCargaIntf.pas',
  LineaHojaCargaIntf in '..\..\Interface\Gim40\LineaHojaCargaIntf.pas',
  dmi_ifv117 in '..\..\Interface\Gim117\dmi_ifv117.pas',
  b_nda in '..\Gdm40\b_nda.pas' {BoxNdaForm: TgForm},
  dmi_art in '..\..\Interface\Gim30\dmi_art.pas',
  ClienteIntf in '..\..\Interface\Gim10\ClienteIntf.pas',
  NexusRpcData in '..\..\Lib\NexusRpcData.pas' {NexusRpcDataModule: TDataModule},
  PDFViewer in '..\..\Lib\PDFViewer.pas' {PDFViewerForm: TgForm},
  i_rdr in '..\Gdm10\i_rdr.pas' {RptRdrForm: TgForm},
  Gdm70Dm in '..\Gdm70\Gdm70Dm.pas' {DataModule70: TDataModule},
  dmi_sen in '..\..\Interface\Gim203\dmi_sen.pas',
  Gim70Fields in '..\..\Interface\Gim70\Gim70Fields.pas',
  l_tcm in '..\Gdm201\l_tcm.pas' {RptTcmForm: TgForm},
  dmi_iva in '..\..\Interface\Gim10\dmi_iva.pas',
  dm_cdc in '..\Gdm70\dm_cdc.pas' {CodigoCosteModule: TDataModule},
  dmi_odf in '..\..\Interface\Gim70\dmi_odf.pas',
  b_lan in '..\Gdm70\b_lan.pas' {BoxLanForm: TgForm},
  dm_odf in '..\Gdm70\dm_odf.pas' {OrdenFabricacionModule: TDataModule},
  f_cnf70 in '..\Gdm70\f_cnf70.pas' {ProduccionModule: TDataModule},
  a_pde7 in '..\Gdm70\a_pde7.pas' {MntPde7Form: TgForm},
  f_cnf208 in '..\Gdm208\f_cnf208.pas' {SuministroInformacionModule: TDataModule},
  OrdenFabricacionIntf in '..\..\Interface\Gim70\OrdenFabricacionIntf.pas',
  dmi_cla in '..\..\Interface\Gim70\dmi_cla.pas',
  dmi_lmp in '..\..\Interface\Gim70\dmi_lmp.pas',
  dmi_cpr in '..\..\Interface\Gim70\dmi_cpr.pas',
  dmi_maq in '..\..\Interface\Gim70\dmi_maq.pas',
  dmi_idf in '..\..\Interface\Gim70\dmi_idf.pas',
  InformeFabricacionIntf in '..\..\Interface\Gim70\InformeFabricacionIntf.pas',
  gdm10Dm in '..\Gdm10\gdm10Dm.pas' {DataModule10: TDataModule},
  FacturaComprasIntf in '..\..\Interface\Gim30\FacturaComprasIntf.pas',
  b_dtp in '..\Gdm70\b_dtp.pas' {BoxDtpForm: TgForm},
  b_ccf in '..\Gdm70\b_ccf.pas' {BoxCcfForm: TgForm},
  dmi_ccf in '..\..\Interface\Gim70\dmi_ccf.pas',
  dmi_rdip in '..\..\Interface\Gim70\dmi_rdip.pas',
  b_tbf in '..\Gdm205\b_tbf.pas' {TabletaFirmaForm: TgForm},
  dm_tbf in '..\Gdm205\dm_tbf.pas' {TabletaFirmaDataModule: TDataModule},
  wgssSTU_TLB in '..\Gdm205\wgssSTU_TLB.pas',
  b_rra in '..\Gdm207\b_rra.pas' {BoxRraForm: TgForm},
  dmi_cfg105 in '..\..\Interface\Gim105\dmi_cfg105.pas',
  b_blp in '..\Gdm10\b_blp.pas' {BoxBlpForm: TgForm},
  Gim114Fields in '..\..\Interface\Gim114\Gim114Fields.pas',
  dmi_cnd in '..\..\Interface\Gim00\dmi_cnd.pas',
  dmi_dcm114 in '..\..\Interface\Gim114\dmi_dcm114.pas',
  a_fcg in '..\Gdm10\a_fcg.pas' {MntFcgForm: TgForm},
  a_fvi in '..\Gdm10\a_fvi.pas' {MntFviForm: TgForm},
  dm_sfr in '..\Gdm10\dm_sfr.pas' {SFRecibidasModule: TDataModule},
  b_sfa in '..\Gdm208\b_sfa.pas' {BoxSfaForm: TgForm},
  dmi_nda in '..\..\Interface\Gim40\dmi_nda.pas',
  gdm40Frm in '..\Gdm40\gdm40Frm.pas' {gds40Frm: TFrame},
  AppForms in '..\..\Lib\AppForms.pas' {ApplicationForms: TFrame},
  dm_nda in '..\Gdm40\dm_nda.pas' {AprovisionamientoModule: TDataModule},
  dm_idf in '..\Gdm70\dm_idf.pas' {InformeFabricacionModule: TDataModule},
  b_rof in '..\Gdm70\b_rof.pas' {BoxRofForm: TgForm},
  b_sdt207 in '..\Gdm207\b_sdt207.pas' {BoxSdt207Form: TgForm},
  dm_sdt207 in '..\Gdm207\dm_sdt207.pas' {SincronizacionTiendaMagentoModule: TDataModule},
  dm_tvr in '..\Gdm207\dm_tvr.pas' {TiendaVirtualModule: TDataModule},
  dmi_pve in '..\..\Interface\Gim30\dmi_pve.pas',
  b_test207 in '..\Gdm207\b_test207.pas' {BoxTest207Form: TgForm},
  b_odf_1 in '..\Gdm70\b_odf_1.pas' {BoxOdf1Frame: TFrame},
  a_pde_con in '..\Gdm10\a_pde_con.pas' {BoxPdeConForm: TgForm},
  a_pde_art in '..\Gdm30\a_pde_art.pas' {BoxPdeArtForm: TgForm},
  a_pde_cli in '..\Gdm30\a_pde_cli.pas' {BoxPdeCliForm: TgForm},
  a_pde_pro in '..\Gdm30\a_pde_pro.pas' {BoxPdeProForm: TgForm},
  a_pde_com in '..\Gdm30\a_pde_com.pas' {BoxPdeComForm: TgForm},
  a_pde_ven in '..\Gdm30\a_pde_ven.pas' {BoxPdeVenForm: TgForm},
  Gim60Fields in '..\..\Interface\Gim60\Gim60Fields.pas',
  Gim119Fields in '..\..\Interface\Gim119\Gim119Fields.pas',
  b_atf in '..\Gdm70\b_atf.pas' {BoxAtfForm: TgForm},
  b_2fa in '..\Gdm207\b_2fa.pas' {Box2faForm: TgForm},
  ComPort in '..\..\Lib\ComPort.pas',
  l_bei in '..\Gdm10\l_bei.pas' {RptBeiForm: TgForm},
  AppContainer in '..\..\Lib\AppContainer.pas' {ApplicationContainer: TFrame},
  b_roi in '..\Gdm204\b_roi.pas' {BoxRolForm: TgxForm},
  f_grd in '..\..\Lib\f_grd.pas' {GridOutputFrame: TFrame},
  DashBoardSection in '..\..\Lib\DashBoardSection.pas' {DashBoardSectionFrame: TFrame},
  dm_bei in '..\Gdm10\dm_bei.pas' {BalancesInformesModule: TDataModule},
  QueryFormBar in '..\..\Lib\QueryFormBar.pas' {QueryFormBarFrame: TFrame},
  QueryGrid in '..\..\Lib\QueryGrid.pas' {QueryGridFrame: TFrame},
  b_rfe in '..\Gdm200\b_rfe.pas' {BoxRfeForm: TgxForm},
  b_ife in '..\Gdm200\b_ife.pas' {BoxIfeForm: TgxForm},
  AppForm in '..\GdLib\AppForm.pas' {ApplicationForm: TgxForm},
  FacturaIntf in '..\..\Interface\Gim10\FacturaIntf.pas',
  dmi_pga in '..\..\Interface\Gim00\dmi_pga.pas',
  dm_fce in '..\Gdm200\dm_fce.pas' {FacturaElectronicaDataModule: TDataModule},
  dm_cer in '..\Gdm00\dm_cer.pas' {CertificadosModule: TDataModule},
  dmi_iex in '..\..\Interface\Gim00\dmi_iex.pas',
  dm_ptv in '..\Gdm207\dm_ptv.pas' {ParametrosTiendaVirtualModule: TDataModule},
  a_odu in '..\Gdm00\a_odu.pas' {MntOduForm: TgxForm},
  f_fco in '..\Gdm200\f_fco.pas' {FcoFrame: TFrame},
  f_dsb_cbl in '..\Gdm00\f_dsb_cbl.pas' {DashboardChartBarLineFrame: TFrame},
  f_dsb_cdo in '..\Gdm00\f_dsb_cdo.pas' {DashboardChartDonutFrame: TFrame},
  f_dsb_prb in '..\Gdm00\f_dsb_prb.pas' {DashboardProgressLineFrame: TFrame},
  Dashboard in '..\..\Lib\Dashboard.pas' {DashboardForm: TgxForm},
  dm_sfe in '..\Gdm10\dm_sfe.pas' {SFEmitidasModule: TDataModule},
  a_art in '..\Gdm30\a_art.pas' {MntArtForm: TgxForm},
  f_art_tvr in '..\Gdm207\f_art_tvr.pas' {MntArtTvrFrame: TFrame},
  a_arq in '..\Gdm20\a_arq.pas' {mntArqForm: TgxForm},
  gdm20Frm in '..\Gdm20\gdm20Frm.pas' {Gds20Frm: TFrame},
  f_tpv in '..\Gdm20\f_tpv.pas' {TPVModule: TDataModule},
  SuministroFactRecibidas in '..\Gdm10\SuministroFactRecibidas.pas',
  SuministroFactEmitidas in '..\Gdm10\SuministroFactEmitidas.pas',
  dm_rpf in '..\Gdm10\dm_rpf.pas' {RegistroPresentacionModule: TDataModule},
  dmi_rpf in '..\..\Interface\Gim10\dmi_rpf.pas',
  gdc.dxSettings in 'gdc.dxSettings.pas',
  f_not in '..\..\Lib\Custom\FastReport\Source\f_not.pas' {AnnotationFrame: TFrame},
  LibUtils in '..\..\Lib\LibUtils.pas',
  DataManager in '..\..\Lib\DataManager.pas',
  DataAccess in '..\..\Lib\DataAccess.pas' {DataAccessModule: TDataModule},
  ReportManager in '..\..\Lib\Custom\FastReport\Source\ReportManager.pas' {ReportManagerDataModule: TDataModule},
  Gdm00Frm in '..\Gdm00\Gdm00Frm.pas' {Gds00Frm: TFrame},
  Gdm00Dm in '..\Gdm00\Gdm00Dm.pas' {DataModule00: TDataModule},
  Presentacion in '..\Gdm00\Presentacion.pas' {PresentacionForm},
  dm_ine in '..\Gdm00\dm_ine.pas' {InformeExternoModule: TDataModule},
  dm_pga in '..\Gdm00\dm_pga.pas' {ConfiguracionModule: TDataModule},
  dm_cnd in '..\Gdm00\dm_cnd.pas' {ContadoresModule: TDataModule},
  b_upd in '..\Gdm00\b_upd.pas' {BoxUpdForm: TgForm},
  b_bck in '..\Gdm00\b_bck.pas' {BoxBckForm: TgxForm},
  b_msg in '..\..\Lib\b_msg.pas' {MsgBoxForm: TgxForm},
  b_uee in '..\Gdm00\b_uee.pas' {BoxUeeForm: TgxForm},
  l_usr in '..\Gdm00\l_usr.pas' {rptUsrForm: TgxForm},
  a_emp in '..\Gdm00\a_emp.pas' {MntEmpForm: TgxForm},
  l_emp in '..\Gdm00\l_emp.pas' {rptEmpForm: TgxForm},
  a_prv in '..\Gdm00\a_prv.pas' {mntPrvForm: TgxForm},
  l_prv in '..\Gdm00\l_prv.pas' {rptPrvForm: TgxForm},
  a_pai in '..\Gdm00\a_pai.pas' {mntPaiForm: TgxForm},
  l_pai in '..\Gdm00\l_pai.pas' {rptPaiForm: TgxForm},
  a_cop in '..\Gdm00\a_cop.pas' {MntCopForm: TgxForm},
  l_cop in '..\Gdm00\l_cop.pas' {rptCopForm: TgxForm},
  a_cdi in '..\Gdm00\a_cdi.pas' {mntCdiForm: TgxForm},
  l_cdi in '..\Gdm00\l_cdi.pas' {rptCdiForm: TgxForm},
  a_enf in '..\Gdm00\a_enf.pas' {MntEnfForm: TgxForm},
  a_efx in '..\Gdm00\a_efx.pas' {MntEfxForm: TgxForm},
  a_tca in '..\Gdm00\a_tca.pas' {MntTcaForm: TgxForm},
  l_tca in '..\Gdm00\l_tca.pas' {rptTcaForm: TgxForm},
  a_ddc in '..\Gdm00\a_ddc.pas' {mntDdcForm: TgxForm},
  l_ddc in '..\Gdm00\l_ddc.pas' {rptDdcForm: TgxForm},
  a_acc in '..\Gdm00\a_acc.pas' {MntAccForm: TgxForm},
  a_pga in '..\Gdm00\a_pga.pas' {MntPgaForm: TgxForm},
  a_ine in '..\Gdm00\a_ine.pas' {mntIneForm: TgxForm},
  l_ine in '..\Gdm00\l_ine.pas' {RptIneForm: TgxForm},
  a_imp in '..\Gdm00\a_imp.pas' {MntImpForm: TgxForm},
  l_imp in '..\Gdm00\l_imp.pas' {RptImpForm: TgxForm},
  a_fic in '..\Gdm00\a_fic.pas' {mntFicForm: TgxForm},
  a_cer in '..\Gdm00\a_cer.pas' {MntCerForm: TgForm},
  a_ccr in '..\Gdm00\a_ccr.pas' {MntCcrForm: TgxForm},
  b_afr in '..\Gdm00\b_afr.pas' {mntAfrForm: TgxForm},
  b_rdf in '..\Gdm00\b_rdf.pas' {MntRdfForm: TgxForm},
  b_efm in '..\Gdm00\b_efm.pas' {boxEfmForm: TgxForm},
  b_ddp in '..\Gdm00\b_ddp.pas' {mntDdpForm: TgxForm},
  a_sub in '..\Gdm10\a_sub.pas' {MntSubForm: TgxForm},
  a_con in '..\Gdm10\a_con.pas' {mntConForm: TgxForm},
  a_tas in '..\Gdm10\a_tas.pas' {mntTasForm: TgxForm},
  a_cco in '..\Gdm10\a_cco.pas' {mntCCoForm: TgxForm},
  a_can in '..\Gdm10\a_can.pas' {MntCanForm: TgxForm},
  a_ast in '..\Gdm10\a_ast.pas' {MntAstForm: TgxForm},
  b_ext in '..\Gdm10\b_ext.pas' {brwExtForm: TgxForm},
  b_pun in '..\Gdm10\b_pun.pas' {BrwPunForm: TgxForm},
  b_sal in '..\Gdm10\b_sal.pas' {BrwSalForm: TgxForm},
  l_dia in '..\Gdm10\l_dia.pas' {rptDiaForm: TgxForm},
  l_dir in '..\Gdm10\l_dir.pas' {rptDirForm: TgxForm},
  l_ext in '..\Gdm10\l_ext.pas' {rptExtForm: TgxForm},
  l_sda in '..\Gdm10\l_sda.pas' {RptSdaForm: TgxForm},
  l_bmp in '..\Gdm10\l_bmp.pas' {rptBmpForm: TgxForm},
  l_bss in '..\Gdm10\l_bss.pas' {rptBssForm: TgxForm},
  p_con in '..\Gdm10\p_con.pas' {GestionContableFrame: TDashBoardSectionFrame},
  l_pyg in '..\Gdm10\l_pyg.pas' {RptPygForm: TgxForm},
  l_bsi in '..\Gdm10\l_bsi.pas' {RptBsiForm: TgxForm},
  l_cpn in '..\Gdm10\l_cpn.pas' {RptCpnForm: TgxForm},
  g_sal in '..\Gdm10\g_sal.pas' {GphSalForm},
  a_exi in '..\Gdm10\a_exi.pas' {mntExiForm: TgxForm},
  b_rsa in '..\Gdm10\b_rsa.pas' {BoxRsaForm: TgxForm},
  b_rda in '..\Gdm10\b_rda.pas' {BoxRdaForm: TgxForm},
  b_ccn in '..\Gdm10\b_ccn.pas' {BoxCcnForm: TgxForm},
  b_iex in '..\Gdm10\b_iex.pas' {BoxIexForm: TgxForm},
  b_ea3 in '..\Gdm10\b_ea3.pas' {boxEA3Form: TgxForm},
  b_sds in '..\Gdm10\b_sds.pas' {BoxSdsForm: TgxForm},
  b_cde in '..\Gdm10\b_cde.pas' {boxCdeForm: TgxForm},
  b_vec in '..\Gdm10\b_vec.pas' {BoxVecForm: TgxForm},
  a_pde_tpv in '..\Gdm20\a_pde_tpv.pas' {BoxPdeTPVForm: TgxForm},
  Gdm20Dm in '..\Gdm20\Gdm20Dm.pas' {DataModule20: TDataModule},
  a_alm in '..\Gdm30\a_alm.pas' {MntAlmForm: TgxForm},
  a_cdb in '..\Gdm30\a_cdb.pas' {MntCdbForm: TgxForm},
  a_cdp in '..\Gdm30\a_cdp.pas' {MntCdpForm: TgxForm},
  a_cdt in '..\Gdm30\a_cdt.pas' {MntCdtForm: TgxForm},
  a_chc in '..\Gdm30\a_chc.pas' {MntChcForm: TgxForm},
  a_cls in '..\Gdm30\a_cls.pas' {MntClsForm: TgxForm},
  a_clsa in '..\Gdm30\a_clsa.pas' {MntClsaForm: TgxForm},
  a_cpt in '..\Gdm30\a_cpt.pas' {mntCptForm: TgxForm},
  a_eqm in '..\Gdm30\a_eqm.pas' {mntEqmForm: TgxForm},
  a_fam in '..\Gdm30\a_fam.pas' {MntFamForm: TgxForm},
  a_fdc in '..\Gdm30\a_fdc.pas' {MntFdcForm: TgxForm},
  a_fde in '..\Gdm30\a_fde.pas' {MntFdeForm: TgxForm},
  a_fdv in '..\Gdm30\a_fdv.pas' {MntFdvForm: TgxForm},
  a_gdc in '..\Gdm30\a_gdc.pas' {MntGdcForm: TgxForm},
  a_gdo in '..\Gdm30\a_gdo.pas' {MntGdoForm: TgxForm},
  a_gdp in '..\Gdm30\a_gdp.pas' {MntGdpForm: TgxForm},
  a_lma in '..\Gdm30\a_lma.pas' {mntLmaForm: TgxForm},
  a_mco in '..\Gdm30\a_mco.pas' {MntMcoForm: TgxForm},
  a_mov in '..\Gdm30\a_mov.pas' {MntMovForm: TgxForm},
  a_mve in '..\Gdm30\a_mve.pas' {MntMveForm: TgxForm},
  a_ope in '..\Gdm30\a_ope.pas' {MntOpeForm: TgxForm},
  a_orp in '..\Gdm30\a_orp.pas' {MntOrpForm: TgxForm},
  a_pde_alm in '..\Gdm30\a_pde_alm.pas' {BoxPdeAlmForm: TgxForm},
  a_pea in '..\Gdm30\a_pea.pas' {MntPeaForm: TgxForm},
  a_pec in '..\Gdm30\a_pec.pas' {MntPecForm: TgxForm},
  a_pep in '..\Gdm30\a_pep.pas' {MntPepForm: TgxForm},
  a_pev in '..\Gdm30\a_pev.pas' {MntPevForm: TgxForm},
  a_rac in '..\Gdm30\a_rac.pas' {MntRacForm: TgxForm},
  a_rap in '..\Gdm30\a_rap.pas' {MntRapForm: TgxForm},
  a_rcc in '..\Gdm30\a_rcc.pas' {MntRccForm: TgxForm},
  a_rut in '..\Gdm30\a_rut.pas' {MntRutForm: TgxForm},
  a_rvf in '..\Gdm30\a_rvf.pas' {MntRvfForm: TgxForm},
  a_rvv in '..\Gdm30\a_rvv.pas' {MntRvvForm: TgxForm},
  a_tcc in '..\Gdm30\a_tcc.pas' {MntTccForm: TgxForm},
  a_rcf in '..\Gdm30\a_rcf.pas' {mntRcfForm: TgxForm},
  a_rgc in '..\Gdm30\a_rgc.pas' {MntRgcForm: TgxForm},
  a_tck in '..\Gdm30\a_tck.pas' {MntTckForm: TgxForm},
  a_tcn in '..\Gdm30\a_tcn.pas' {MntTcnForm: TgxForm},
  a_tcoa in '..\Gdm30\a_tcoa.pas' {MntTcoaForm: TgxForm},
  a_tcof in '..\Gdm30\a_tcof.pas' {MntTcofForm: TgxForm},
  a_tct in '..\Gdm30\a_tct.pas' {MntTctForm: TgxForm},
  a_tcv in '..\Gdm30\a_tcv.pas' {MntTcvForm: TgxForm},
  a_tde in '..\Gdm30\a_tde.pas' {MntTdeForm: TgxForm},
  a_tip in '..\Gdm30\a_tip.pas' {MntTipForm: TgxForm},
  a_tla in '..\Gdm30\a_tla.pas' {MntTlaForm: TgxForm},
  a_tlf in '..\Gdm30\a_tlf.pas' {MntTlfForm: TgxForm},
  a_tlm in '..\Gdm30\a_tlm.pas' {MntTlmForm: TgxForm},
  a_tma in '..\Gdm30\a_tma.pas' {MntTmaForm: TgxForm},
  a_tpp in '..\Gdm30\a_tpp.pas' {MntTppForm: TgxForm},
  a_tra in '..\Gdm30\a_tra.pas' {MntTraForm: TgxForm},
  a_tva in '..\Gdm30\a_tva.pas' {MntTvaForm: TgxForm},
  a_tvf in '..\Gdm30\a_tvf.pas' {MntTvfForm: TgxForm},
  a_tvp in '..\Gdm30\a_tvp.pas' {MntTvpForm: TgxForm},
  a_ubi in '..\Gdm30\a_ubi.pas' {mntUbiForm: TgxForm},
  a_ven in '..\Gdm30\a_ven.pas' {MntVenForm: TgxForm},
  a_vpe in '..\Gdm30\a_vpe.pas' {mntVpeForm: TgxForm},
  b_aal in '..\Gdm30\b_aal.pas' {BoxAalForm: TgxForm},
  b_avp in '..\Gdm30\b_avp.pas' {BoxAvpForm: TgxForm},
  b_bpf in '..\Gdm30\b_bpf.pas' {BoxBpfForm: TgxForm},
  b_cac in '..\Gdm30\b_cac.pas' {BrwCacForm: TgxForm},
  b_ccc in '..\Gdm30\b_ccc.pas' {BoxCccForm: TgxForm},
  b_ccv in '..\Gdm30\b_ccv.pas' {BoxCcvForm: TgxForm},
  b_cdc in '..\Gdm30\b_cdc.pas' {BoxCdcForm: TgxForm},
  b_cdv in '..\Gdm30\b_cdv.pas' {BoxCdvForm: TgxForm},
  b_cec in '..\Gdm30\b_cec.pas' {BoxCecForm: TgxForm},
  b_cem in '..\Gdm30\b_cem.pas' {boxCemForm: TgxForm},
  b_chc in '..\Gdm30\b_chc.pas' {boxChcForm: TgxForm},
  b_cma in '..\Gdm30\b_cma.pas' {boxCmaForm: TgxForm},
  b_cmp in '..\Gdm30\b_cmp.pas' {BoxCmpForm: TgxForm},
  b_cmr in '..\Gdm30\b_cmr.pas' {BoxCmrForm: TgxForm},
  b_cpa in '..\Gdm30\b_cpa.pas' {BrwCpaForm: TgxForm},
  b_crt in '..\Gdm30\b_crt.pas' {BoxCrtForm: TgxForm},
  b_ctc in '..\Gdm30\b_ctc.pas' {BoxCtcForm: TgxForm},
  b_ctp in '..\Gdm30\b_ctp.pas' {BoxCtpForm: TgxForm},
  b_drc in '..\Gdm30\b_drc.pas' {boxDrcForm: TgxForm},
  b_ear in '..\Gdm30\b_ear.pas' {BoxEarForm: TgxForm},
  b_eda in '..\Gdm30\b_eda.pas' {BrwEdaForm: TgxForm},
  b_edc in '..\Gdm30\b_edc.pas' {BoxEdcForm: TgxForm},
  b_edv in '..\Gdm30\b_edv.pas' {BoxEdvForm: TgxForm},
  b_eea in '..\Gdm30\b_eea.pas' {brwEeaForm: TgxForm},
  b_efc in '..\Gdm30\b_efc.pas' {BoxEfcForm: TgxForm},
  b_efv in '..\Gdm30\b_efv.pas' {BoxEfvForm: TgxForm},
  b_ema in '..\Gdm30\b_ema.pas' {BoxEmaForm: TgxForm},
  b_emc in '..\Gdm30\b_emc.pas' {BoxEmcForm: TgxForm},
  b_emv in '..\Gdm30\b_emv.pas' {BoxEmvForm: TgxForm},
  b_fda in '..\Gdm30\b_fda.pas' {BrwFdaForm: TgxForm},
  b_fdc in '..\Gdm30\b_fdc.pas' {BoxFdcForm: TgxForm},
  b_ffa in '..\Gdm30\b_ffa.pas' {boxFfaForm: TgxForm},
  b_gcc in '..\Gdm30\b_gcc.pas' {boxGccForm: TgxForm},
  b_gvp in '..\Gdm30\b_gvp.pas' {BoxGvpForm: TgxForm},
  b_iar in '..\Gdm30\b_iar.pas' {BoxIarForm: TgxForm},
  b_iea in '..\Gdm30\b_iea.pas' {BoxIeaForm: TgxForm},
  b_lcl in '..\Gdm30\b_lcl.pas' {BoxLclForm: TgxForm},
  b_mco in '..\Gdm30\b_mco.pas' {BoxMcoForm: TgxForm},
  b_mve in '..\Gdm30\b_mve.pas' {BoxMveForm: TgxForm},
  b_rcc in '..\Gdm30\b_rcc.pas' {BrwRccForm: TgxForm},
  b_rdp in '..\Gdm30\b_rdp.pas' {BrwRdpForm: TgxForm},
  b_rdr in '..\Gdm30\b_rdr.pas' {BoxRdrForm: TgxForm},
  b_rfc in '..\Gdm30\b_rfc.pas' {boxRfcForm: TgxForm},
  b_rfv in '..\Gdm30\b_rfv.pas' {BoxRfvForm: TgxForm},
  b_rld in '..\Gdm30\b_rld.pas' {BrwRlvForm: TgxForm},
  b_rrc in '..\Gdm30\b_rrc.pas' {BoxRrcForm: TgxForm},
  b_rmv in '..\Gdm30\b_rmv.pas' {BoxRmvForm: TgxForm},
  b_rcp in '..\Gdm30\b_rcp.pas' {BrwRcpForm: TgxForm},
  b_rdc in '..\Gdm30\b_rdc.pas' {BrwRdcForm: TgxForm},
  b_rdm in '..\Gdm30\b_rdm.pas' {BrwRdmForm: TgxForm},
  b_sac in '..\Gdm30\b_sac.pas' {BoxSacForm: TgxForm},
  b_sav in '..\Gdm30\b_sav.pas' {BoxSavForm: TgxForm},
  b_sdc in '..\Gdm30\b_sdc.pas' {BoxSdcForm: TgxForm},
  b_sdv in '..\Gdm30\b_sdv.pas' {BoxSdvForm: TgxForm},
  b_sfv in '..\Gdm30\b_sfv.pas' {BoxSfvForm: TgxForm},
  b_spe in '..\Gdm30\b_spe.pas' {BoxSpvForm: TgxForm},
  b_sua in '..\Gdm30\b_sua.pas' {boxSuaForm: TgxForm},
  b_suf in '..\Gdm30\b_suf.pas' {BoxSufForm: TgxForm},
  b_sup in '..\Gdm30\b_sup.pas' {BoxSupForm: TgxForm},
  b_trz in '..\Gdm30\b_trz.pas' {BoxTrzForm: TgxForm},
  b_vpa in '..\Gdm30\b_vpa.pas' {BrwVpaForm: TgxForm},
  c_art in '..\Gdm30\c_art.pas' {CnsArtForm: TgxForm},
  cm_fcg in '..\Gdm30\cm_fcg.pas' {CmdFcgModule: TDataModule},
  cm_fvi in '..\Gdm30\cm_fvi.pas' {CmdFviModule: TDataModule},
  cm_man in '..\Gdm30\cm_man.pas' {CmdManModule: TDataModule},
  cm_mdc in '..\Gdm30\cm_mdc.pas' {CmdMdcModule: TDataModule},
  cm_rdr in '..\Gdm30\cm_rdr.pas' {CmdRdrModule: TDataModule},
  cx_alm in '..\Gdm30\cx_alm.pas' {cxAlmForm: TgxForm},
  cx_fde in '..\Gdm30\cx_fde.pas' {cxFdeForm: TgxForm},
  cx_fdv in '..\Gdm30\cx_fdv.pas' {CxFdvForm: TgxForm},
  cx_gdc in '..\Gdm30\cx_gdc.pas' {cxGdcForm: TgxForm},
  cx_gdo in '..\Gdm30\cx_gdo.pas' {cxGdoForm: TgxForm},
  cx_gdp in '..\Gdm30\cx_gdp.pas' {CxGdpForm: TgxForm},
  cx_ldp1 in '..\Gdm30\cx_ldp1.pas' {CxLdp1Form: TgxForm},
  cx_ldp2 in '..\Gdm30\cx_ldp2.pas' {CxLdp2Form: TgxForm},
  cx_lma in '..\Gdm30\cx_lma.pas' {cxLmaForm: TgxForm},
  cx_mco in '..\Gdm30\cx_mco.pas' {CxMcoForm: TgxForm},
  cx_mov in '..\Gdm30\cx_mov.pas' {CxMovForm: TgxForm},
  cx_mve in '..\Gdm30\cx_mve.pas' {CxMveForm: TgxForm},
  cx_nds in '..\Gdm30\cx_nds.pas' {CxNdsForm: TgxForm},
  cx_ope in '..\Gdm30\cx_ope.pas' {CxOpeForm: TgxForm},
  cx_orp in '..\Gdm30\cx_orp.pas' {CxOrpForm: TgxForm},
  cx_plm in '..\Gdm30\cx_plm.pas' {cxPlmForm: TgxForm},
  cx_rac in '..\Gdm30\cx_rac.pas' {CxRacForm: TgxForm},
  cx_rap in '..\Gdm30\cx_rap.pas' {CxRapForm: TgxForm},
  cx_rut in '..\Gdm30\cx_rut.pas' {CxRutForm: TgxForm},
  cx_tcv in '..\Gdm30\cx_tcv.pas' {CxTcvForm: TgxForm},
  cx_tde in '..\Gdm30\cx_tde.pas' {cxTdeForm: TgxForm},
  cx_tdv in '..\Gdm30\cx_tdv.pas' {CxTdvForm: TgxForm},
  cx_tlm in '..\Gdm30\cx_tlm.pas' {cxTlmForm: TgxForm},
  cx_tma in '..\Gdm30\cx_tma.pas' {cxTmaForm: TgxForm},
  cx_tra in '..\Gdm30\cx_tra.pas' {CxTraForm: TgxForm},
  cx_tvp in '..\Gdm30\cx_tvp.pas' {cxTvpForm: TgxForm},
  cx_ubi in '..\Gdm30\cx_ubi.pas' {cxUbiForm: TgxForm},
  cx_ven in '..\Gdm30\cx_ven.pas' {CxVenForm: TgxForm},
  cx_vpe in '..\Gdm30\cx_vpe.pas' {CxVpeForm: TgxForm},
  d_art in '..\Gdm30\d_art.pas' {BrwArtForm: TgxForm},
  d_cli in '..\Gdm30\d_cli.pas' {BrwCliForm: TgxForm},
  d_pro in '..\Gdm30\d_pro.pas' {BrwProForm: TgxForm},
  d_ven in '..\Gdm30\d_ven.pas' {brwVenForm: TgxForm},
  dm_alm in '..\Gdm30\dm_alm.pas' {AlmacenModule: TDataModule},
  dm_art in '..\Gdm30\dm_art.pas' {ArticuloModule: TDataModule},
  dm_cdb in '..\Gdm30\dm_cdb.pas' {CodigoBarrasModule: TDataModule},
  dm_cdt in '..\Gdm30\dm_cdt.pas' {CodigoTarifaModule: TDataModule},
  dm_cec in '..\Gdm30\dm_cec.pas' {CierreComercialModule: TDataModule},
  dm_cls in '..\Gdm30\dm_cls.pas' {ClaseModule: TDataModule},
  dm_cpt in '..\Gdm30\dm_cpt.pas' {CapturadorModule: TDataModule},
  dm_efe in '..\Gdm30\dm_efe.pas' {EfectoModule: TDataModule},
  dm_eqm in '..\Gdm30\dm_eqm.pas' {EquipoMovilModule: TDataModule},
  dm_fam in '..\Gdm30\dm_fam.pas' {FamiliaModule: TDataModule},
  dm_fdc in '..\Gdm30\dm_fdc.pas' {FacturaComprasModule: TDataModule},
  dm_fde in '..\Gdm30\dm_fde.pas' {FormaEnvioModule: TDataModule},
  dm_fdv in '..\Gdm30\dm_fdv.pas' {FacturaVentasModule: TDataModule},
  dm_gdc in '..\Gdm30\dm_gdc.pas' {GrupoClienteModule: TDataModule},
  dm_gdo in '..\Gdm30\dm_gdo.pas' {GrupoDocumentoModule: TDataModule},
  dm_gdp in '..\Gdm30\dm_gdp.pas' {GrupoProveedorModule: TDataModule},
  dm_lma in '..\Gdm30\dm_lma.pas' {ListaMaterialesModule: TDataModule},
  dm_mov in '..\Gdm30\dm_mov.pas' {MovimientoModule: TDataModule},
  dm_ope in '..\Gdm30\dm_ope.pas' {OperarioModule: TDataModule},
  dm_orp in '..\Gdm30\dm_orp.pas' {OrganismoPublicoModule: TDataModule},
  dm_pve in '..\Gdm30\dm_pve.pas' {PreventaModule: TDataModule},
  dm_rac in '..\Gdm30\dm_rac.pas' {AuxiliarClienteModule: TDataModule},
  dm_rap in '..\Gdm30\dm_rap.pas' {AuxiliarProveedorModule: TDataModule},
  dm_rcl in '..\Gdm30\dm_rcl.pas' {RelacionesClienteModule: TDataModule},
  dm_rdm in '..\Gdm30\dm_rdm.pas' {RelacionDocumentosModule: TDataModule},
  dm_rdr in '..\Gdm30\dm_rdr.pas' {ReconstruccionResultadosModule: TDataModule},
  dm_rea in '..\Gdm30\dm_rea.pas' {RegistroActualizacionModule: TDataModule},
  dm_rpr in '..\Gdm30\dm_rpr.pas' {RelacionesProveedorModule: TDataModule},
  dm_rut in '..\Gdm30\dm_rut.pas' {RutaModule: TDataModule},
  dm_sto in '..\Gdm30\dm_sto.pas' {StockAlmacenModule: TDataModule},
  dm_suf in '..\Gdm30\dm_suf.pas' {SuministroFacturasModule: TDataModule},
  dm_tde in '..\Gdm30\dm_tde.pas' {TipoEnvaseModule: TDataModule},
  dm_tlm in '..\Gdm30\dm_tlm.pas' {TipoLineaMovimientoModule: TDataModule},
  dm_tma in '..\Gdm30\dm_tma.pas' {TipoMovAlmacenModule: TDataModule},
  dm_tra in '..\Gdm30\dm_tra.pas' {TransportistaModule: TDataModule},
  dm_tvp in '..\Gdm30\dm_tvp.pas' {TipoVentaPeriodicaModule: TDataModule},
  dm_ubi in '..\Gdm30\dm_ubi.pas' {UbicacionModule: TDataModule},
  dm_ven in '..\Gdm30\dm_ven.pas' {VendedorModule: TDataModule},
  dm_vpe in '..\Gdm30\dm_vpe.pas' {VentasPeriodicasModule: TDataModule},
  e_art in '..\Gdm30\e_art.pas' {EtqArtForm: TgxForm},
  e_cli in '..\Gdm30\e_cli.pas' {EtqCliForm: TgxForm},
  e_fdv in '..\Gdm30\e_fdv.pas' {EtqFdvForm: TgxForm},
  e_mov in '..\Gdm30\e_mov.pas' {EtqMovForm: TgxForm},
  e_pro in '..\Gdm30\e_pro.pas' {EtqProForm: TgxForm},
  f_art_rel in '..\Gdm30\f_art_rel.pas' {MntArtRelFrame: TFrame},
  f_art_tva in '..\Gdm30\f_art_tva.pas' {MntArtTvaFrame: TFrame},
  f_cli in '..\Gdm30\f_cli.pas' {MntCliFrame: TFrame},
  f_doc in '..\Gdm30\f_doc.pas' {DocFrame: TFrame},
  f_ecc in '..\Gdm30\f_ecc.pas' {EccFrame: TFrame},
  f_pro in '..\Gdm30\f_pro.pas' {MntProFrame: TFrame},
  f_rdc in '..\Gdm30\f_rdc.pas' {RiesgoFrame: TFrame},
  f_sdf in '..\Gdm30\f_sdf.pas' {MntSdfFrame: TFrame},
  f_sfv in '..\Gdm30\f_sfv.pas' {SfvFrame: TFrame},
  f_smv in '..\Gdm30\f_smv.pas' {SmvFrame: TFrame},
  f_sto in '..\Gdm30\f_sto.pas' {StockFrame: TFrame},
  g_dea in '..\Gdm30\g_dea.pas' {GphDeaForm},
  g_dec in '..\Gdm30\g_dec.pas' {GphDecForm},
  g_dep in '..\Gdm30\g_dep.pas' {GphDepForm},
  g_dev in '..\Gdm30\g_dev.pas' {GphDevForm},
  Gdm30Dm in '..\Gdm30\Gdm30Dm.pas' {DataModule30: TDataModule},
  Gdm30Frm in '..\Gdm30\Gdm30Frm.pas' {Gds30Frm: TFrame},
  i_cli in '..\Gdm30\i_cli.pas' {FrpCliForm: TgxForm},
  i_dco in '..\Gdm30\i_dco.pas' {FrpDcoForm: TgxForm},
  i_dpa in '..\Gdm30\i_dpa.pas' {frpDpaForm: TgxForm},
  i_fdc in '..\Gdm30\i_fdc.pas' {FrpFdcForm: TgxForm},
  l_abm in '..\Gdm30\l_abm.pas' {RptAbmForm: TgxForm},
  l_alm in '..\Gdm30\l_alm.pas' {RptAlmForm: TgxForm},
  l_aoc in '..\Gdm30\l_aoc.pas' {RptAocForm: TgxForm},
  l_aov in '..\Gdm30\l_aov.pas' {RptAovForm: TgxForm},
  l_art in '..\Gdm30\l_art.pas' {RptArtForm: TgxForm},
  l_cac in '..\Gdm30\l_cac.pas' {RptCacForm: TgxForm},
  l_cap in '..\Gdm30\l_cap.pas' {RptCapForm: TgxForm},
  l_cav in '..\Gdm30\l_cav.pas' {RptCavForm: TgxForm},
  l_ccl in '..\Gdm30\l_ccl.pas' {RptCclForm: TgxForm},
  l_cdb in '..\Gdm30\l_cdb.pas' {RptCdbForm: TgxForm},
  l_cdt in '..\Gdm30\l_cdt.pas' {RptCdtForm: TgxForm},
  l_chc in '..\Gdm30\l_chc.pas' {RptChcForm: TgxForm},
  l_cli in '..\Gdm30\l_cli.pas' {RptCliForm: TgxForm},
  l_cls in '..\Gdm30\l_cls.pas' {RptClsForm: TgxForm},
  l_cpe in '..\Gdm30\l_cpe.pas' {RptCpeForm: TgxForm},
  l_cpr in '..\Gdm30\l_cpr.pas' {rptCprForm: TgxForm},
  l_cps in '..\Gdm30\l_cps.pas' {RptCpsForm: TgxForm},
  l_cpt in '..\Gdm30\l_cpt.pas' {RptCptForm: TgxForm},
  l_cva in '..\Gdm30\l_cva.pas' {RptCvaForm: TgxForm},
  l_dco in '..\Gdm30\l_dco.pas' {RptDcoForm: TgxForm},
  l_dea in '..\Gdm30\l_dea.pas' {RptDeaForm: TgxForm},
  l_dec in '..\Gdm30\l_dec.pas' {rptDecForm: TgxForm},
  l_dep in '..\Gdm30\l_dep.pas' {RptDepForm: TgxForm},
  l_dev in '..\Gdm30\l_dev.pas' {RptDevForm: TgxForm},
  l_eda in '..\Gdm30\l_eda.pas' {RptEdaForm: TgxForm},
  l_eqm in '..\Gdm30\l_eqm.pas' {RptEqmForm: TgxForm},
  l_fam in '..\Gdm30\l_fam.pas' {RptFamForm: TgxForm},
  l_fda in '..\Gdm30\l_fda.pas' {RptFdaForm: TgxForm},
  l_fdc in '..\Gdm30\l_fdc.pas' {rptFdcForm: TgxForm},
  l_fde in '..\Gdm30\l_fde.pas' {RptFdeForm: TgxForm},
  l_gdc in '..\Gdm30\l_gdc.pas' {RptGdcForm: TgxForm},
  l_gdo in '..\Gdm30\l_gdo.pas' {RptGdoForm: TgxForm},
  l_gdp in '..\Gdm30\l_gdp.pas' {RptGdpForm: TgxForm},
  l_lcv in '..\Gdm30\l_lcv.pas' {rptLcvForm: TgxForm},
  l_lfc in '..\Gdm30\l_lfc.pas' {RptLfcForm: TgxForm},
  l_lfp in '..\Gdm30\l_lfp.pas' {RptLfpForm: TgxForm},
  l_lgc in '..\Gdm30\l_lgc.pas' {RptLgcForm: TgxForm},
  l_lma in '..\Gdm30\l_lma.pas' {RptLmaForm: TgxForm},
  l_oco in '..\Gdm30\l_oco.pas' {RptOcoForm: TgxForm},
  l_ope in '..\Gdm30\l_ope.pas' {RptOpeForm: TgxForm},
  l_orp in '..\Gdm30\l_orp.pas' {RptOrpForm: TgxForm},
  l_ove in '..\Gdm30\l_ove.pas' {RptOveForm: TgxForm},
  l_pco in '..\Gdm30\l_pco.pas' {RptPcoForm: TgxForm},
  l_rac in '..\Gdm30\l_rac.pas' {RptRacForm: TgxForm},
  l_rap in '..\Gdm30\l_rap.pas' {RptRapForm: TgxForm},
  l_rcf in '..\Gdm30\l_rcf.pas' {RptRcfForm: TgxForm},
  l_rgc in '..\Gdm30\l_rgc.pas' {RptRgcForm: TgxForm},
  l_rmv in '..\Gdm30\l_rmv.pas' {RptRmvForm: TgxForm},
  l_rut in '..\Gdm30\l_rut.pas' {RptRutForm: TgxForm},
  l_rvf in '..\Gdm30\l_rvf.pas' {RptRvfForm: TgxForm},
  l_sdf in '..\Gdm30\l_sdf.pas' {RptSdfForm: TgxForm},
  l_tcc in '..\Gdm30\l_tcc.pas' {RptTccForm: TgxForm},
  l_tcn in '..\Gdm30\l_tcn.pas' {RptTcnForm: TgxForm},
  l_tcoa in '..\Gdm30\l_tcoa.pas' {RptTcoaForm: TgxForm},
  l_tcof in '..\Gdm30\l_tcof.pas' {RptTcofForm: TgxForm},
  l_tct in '..\Gdm30\l_tct.pas' {RptTctForm: TgxForm},
  l_tcv in '..\Gdm30\l_tcv.pas' {RptTcvForm: TgxForm},
  l_tde in '..\Gdm30\l_tde.pas' {RptTdeForm: TgxForm},
  l_tla in '..\Gdm30\l_tla.pas' {RptTlaForm: TgxForm},
  l_tlf in '..\Gdm30\l_tlf.pas' {RptTlfForm: TgxForm},
  l_tlm in '..\Gdm30\l_tlm.pas' {RptTlmForm: TgxForm},
  l_tma in '..\Gdm30\l_tma.pas' {RptTmaForm: TgxForm},
  l_tpp in '..\Gdm30\l_tpp.pas' {RptTppForm: TgxForm},
  l_tra in '..\Gdm30\l_tra.pas' {RptTraForm: TgxForm},
  l_tva in '..\Gdm30\l_tva.pas' {RptTvaForm: TgxForm},
  l_tvf in '..\Gdm30\l_tvf.pas' {RptTvfForm: TgxForm},
  l_tvp in '..\Gdm30\l_tvp.pas' {RptTvpForm: TgxForm},
  l_uba in '..\Gdm30\l_uba.pas' {RptUbaForm: TgxForm},
  l_ubi in '..\Gdm30\l_ubi.pas' {RptUbiForm: TgxForm},
  l_uda in '..\Gdm30\l_uda.pas' {RptUdaForm: TgxForm},
  l_ven in '..\Gdm30\l_ven.pas' {RptVenForm: TgxForm},
  l_vpa in '..\Gdm30\l_vpa.pas' {RptVpaForm: TgxForm},
  l_vpe in '..\Gdm30\l_vpe.pas' {RptVpeForm: TgxForm},
  m_art in '..\Gdm30\m_art.pas' {EdcArtForm: TgxForm},
  m_cpr in '..\Gdm30\m_cpr.pas' {CprQueryModule: TPersistentQueryModule},
  m_cps in '..\Gdm30\m_cps.pas' {CpsQueryModule: TPersistentQueryModule},
  m_vpa in '..\Gdm30\m_vpa.pas' {VpaQueryModule: TPersistentQueryModule},
  q_cpr in '..\Gdm30\q_cpr.pas' {GridCprForm: TgxForm},
  q_cps in '..\Gdm30\q_cps.pas' {GridCpsForm: TgxForm},
  q_vpa in '..\Gdm30\q_vpa.pas' {GridVpaForm: TgxForm},
  r_fdv in '..\Gdm30\r_fdv.pas' {RptFdvForm: TgxForm},
  r_mov in '..\Gdm30\r_mov.pas' {RptMovForm: TgxForm},
  SistemaFacturacion in '..\Gdm30\SistemaFacturacion.pas',
  l_fpc in '..\Gdm10\l_fpc.pas' {rptFpcForm: TgxForm},
  a_edi in '..\Gdm10\a_edi.pas' {MntEdiForm: TgxForm},
  b_gaa in '..\Gdm10\b_gaa.pas' {boxGaaForm: TgxForm},
  dm_reg in '..\Gdm00\dm_reg.pas' {RegistroModule: TDataModule},
  b_test01 in '..\Gdm199\b_test01.pas' {boxTest01Form: TgxForm},
  l_liv in '..\Gdm10\l_liv.pas' {rptLivForm: TgxForm},
  a_rem in '..\Gdm10\a_rem.pas' {MntRemForm: TgxForm},
  a_rdp in '..\Gdm10\a_rdp.pas' {MntRdpForm: TgxForm},
  f_cnf209 in '..\Gdm209\f_cnf209.pas' {Configuracion209Module: TDataModule},
  dmi_cpo in '..\..\Interface\Gim209\dmi_cpo.pas',
  a_pde209 in '..\Gdm209\a_pde209.pas' {MntPde209Form: TgxForm};

{$R *.RES}

// Estas opciones hacen que se cargue toda la aplicación en memoria y evita que se lean páginas desde el servidor cuando se necesitan (entre otras cosas)

const  IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = $8000;

{$SetPEOptFlags IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE}
{$SetPEFlags IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP or IMAGE_FILE_NET_RUN_FROM_SWAP}

procedure DoOnStart;
begin
     // ReportManagerDataModule.DesignReport;
end;

begin

     DebugApp := True;

     { CUIDADO : Las nuevas caracteristicas de NexusDB (4.75 y posteriores) de reducción de mensajes siguen dando problemas de paquetes erróneos,
                 incompletos y otras excepciones desagradables.
                 No se debe activar hasta que el fabricante los solucione (o nunca).
     }

     // Configuración de NexusDB

     nxDisableFeature( nxfClientMessageReduction );
     nxDisableFeature( nxfDelaySetToBookmark );
     nxEnableFeature( nxfAllowLocalFilterForRecordGetBatch );

     ReportMemoryLeaksOnShutdown := True;

     // NeverSleepOnMMThreadContention := True;

     TdxVisualRefinements.LightBorders := True;

     Application.Initialize;

     Application.Title := 'Gestwin 11';

     // ReportEditor := True;

     Application.CreateForm(TApplicationForm, ApplicationForm);
     ShowQueryWithEditor := True;
     ProgramNumber := 3;
     Sp64BitsServer := True;
     ProtectionRec.OptionalModules := 4095;

     Application.MainFormOnTaskbar := False;
     Application.Run;
end.


