program gdd;

{.$DEFINE VIRTUALUI}

(*
  {
    "terminal.integrated.env.windows": {
    "Source":"F:\\Desktop\\Source",
    "App":"F:\\Desktop\\Gestwin",
    "Path":"${Path};F:\\Desktop\\Gestwin"

    },
    "omnipascal.searchPath": "F:\\Desktop\\Source\\*"
   }

   F:\Desktop\Source\Interface\*;F:\Desktop\Source\Lib\Custom\*;F:\Desktop\Source\Lib\Custom\*;F:\Desktop\Source\Lib\*;F:\Desktop\Source\Client\VCL\*

*)

uses
  nxReplacementMemoryManager,
  nxReplacementMove,
  Windows,
  Forms,
  WebBrowser in '..\..\Lib\WebBrowser.pas' {WebForm},
  DataAccess in '..\..\Lib\DataAccess.pas' {DataAccessModule: TDataModule},
  PrintSystem in '..\..\Lib\PrintSystem.pas' {PrintSystemDataModule: TDataModule},
  f_prg in '..\..\Lib\f_prg.pas' {ProcessFrame: TFrame},
  EditableGrid in '..\..\Lib\EditableGrid.pas' {EditableGridFrame: TFrame},
  EnterpriseDataAccess in '..\..\Lib\EnterpriseDataAccess.pas' {EnterpriseDataModule: TDataModule},
  Gdm00Frm in '..\Gdm00\Gdm00Frm.pas' {tartMenu: TFrame},
  Gdm30Frm in '..\Gdm30\Gdm30Frm.pas' {Gds30Frm: TFrame},
  Gdm00Dm in '..\Gdm00\Gdm00Dm.pas' {DataModule00: TDataModule},
  Gdm30Dm in '..\Gdm30\Gdm30Dm.pas' {DataModule30: TDataModule},
  p_gph in '..\Gdm00\p_gph.pas' {GphTemplateForm: TgForm},
  a_tca in '..\Gdm00\a_tca.pas' {MntTcaForm},
  a_cdi in '..\Gdm00\a_cdi.pas' {mntCdiForm},
  a_odu in '..\Gdm03\a_odu.pas' {MntOduForm},
  a_fic in '..\Gdm00\a_fic.pas' {mntFicForm},
  b_sdd in '..\Gdm00\b_sdd.pas' {boxSddForm},
  f_doc in '..\Gdm30\f_doc.pas' {DocFrame: TFrame},
  f_pro in '..\Gdm30\f_pro.pas' {MntProFrame: TFrame},
  gdm90Frm in '..\Gdm90\gdm90Frm.pas' {gds90Frm: TFrame},
  gdm91Frm in '..\Gdm91\gdm91Frm.pas' {gds91Frm: TFrame},
  f_ecc in '..\Gdm30\f_ecc.pas' {EccFrame: TFrame},
  gdm10Frm in '..\Gdm10\gdm10Frm.pas' {Gds10Frm: TFrame},
  Gdm70Frm in '..\Gdm70\Gdm70Frm.pas' {Gds70Frm: TFrame},
  gdm40Dm in '..\Gdm40\gdm40Dm.pas' {DataModule40: TDataModule},
  gdm60Frm in '..\Gdm60\gdm60Frm.pas' {Gds60Frm: TFrame},
  l_lgc in '..\Gdm30\l_lgc.pas' {RptLgcForm},
  cm_rdr in '..\Gdm30\cm_rdr.pas' {CmdRdrModule: TDataModule},
  f_app in '..\Gdm19\f_app.pas' {ApplicationFrame: TFrame},
  f_smv in '..\Gdm30\f_smv.pas' {SmvFrame: TFrame},
  r_mov in '..\Gdm30\r_mov.pas' {RptMcvForm},
  Gdm60Dm in '..\Gdm60\Gdm60Dm.pas' {DataModule60: TDataModule},
  gdm200Dm in '..\Gdm200\gdm200Dm.pas' {DataModule200: TDataModule},
  b_eap in '..\Gdm40\b_eap.pas' {BrwEapForm},
  cm_fcg in '..\Gdm30\cm_fcg.pas' {MntFcgModule: TDataModule},
  f_cpe40 in '..\Gdm40\f_cpe40.pas' {RptCpe40Frame: TDataModule},
  f_sdf in '..\Gdm30\f_sdf.pas' {MntSdfFrame: TFrame},
  b_export in '..\Gdm199\b_export.pas' {BoxExportForm},
  b_import in '..\Gdm199\b_import.pas' {BoxImportForm},
  b_test01 in '..\Gdm199\b_test01.pas' {boxTest01Form},
  f_cnf202 in '..\Gdm202\f_cnf202.pas' {PartidasPresupuestariasModule: TDataModule},
  cm_fvi in '..\Gdm30\cm_fvi.pas' {MntFviModule: TDataModule},
  a_tde in '..\Gdm30\a_tde.pas' {MntTdeForm},
  f_cnf203 in '..\Gdm203\f_cnf203.pas' {EnvasesModule: TDataModule},
  f_cnf204 in '..\Gdm204\f_cnf204.pas' {ExportacionModule: TDataModule},
  gdm203Dm in '..\Gdm203\gdm203Dm.pas' {DataModule203: TDataModule},
  gdm204Dm in '..\Gdm204\gdm204Dm.pas' {DataModule204: TDataModule},
  dm_sen in '..\Gdm203\dm_sen.pas' {StockEnvasesModule: TDataModule},
  i_pck in '..\Gdm204\i_pck.pas' {FrmPckForm},
  Presentacion in '..\Gdm00\Presentacion.pas' {PresentacionForm},
  a_tlm in '..\Gdm30\a_tlm.pas' {MntTlmForm},
  dm_cer in '..\Gdm200\dm_cer.pas',
  cm_man in '..\Gdm30\cm_man.pas' {Man: TFrame},
  f_cli in '..\Gdm30\f_cli.pas' {MntCliFrame: TFrame},
  cx_emp in '..\Gdm00\cx_emp.pas' {CxEmpForm: TgForm},
  a_cli in '..\Gdm10\a_cli.pas' {MntCliForm: TgForm},
  a_pro in '..\Gdm10\a_pro.pas' {mntProForm: TgForm},
  Gim00Fields in '..\..\Interface\Gim00\Gim00Fields.pas',
  Gim10Fields in '..\..\Interface\Gim10\Gim10Fields.pas',
  Gim30Fields in '..\..\Interface\Gim30\Gim30Fields.pas',
  dmi_sal in '..\..\Interface\Gim10\dmi_sal.pas',
  Gim40Fields in '..\..\Interface\Gim40\Gim40Fields.pas',
  AppManager in '..\..\Lib\AppManager.pas',
  dmi_ast in '..\..\Interface\Gim10\dmi_ast.pas',
  LibUtils in '..\..\Lib\LibUtils.pas',
  DataManager in '..\..\Lib\DataManager.pas',
  dmi_ecc in '..\..\Interface\Gim10\dmi_ecc.pas',
  ApunteIntf in '..\..\Interface\Gim10\ApunteIntf.pas',
  AsientoIntf in '..\..\Interface\Gim10\AsientoIntf.pas',
  EfectoCobrarIntf in '..\..\Interface\Gim10\EfectoCobrarIntf.pas',
  b_upd in '..\Gdm00\b_upd.pas' {BoxUpdForm: TgForm},
  dmi_ecp in '..\..\Interface\Gim10\dmi_ecp.pas',
  EfectoPagarIntf in '..\..\Interface\Gim10\EfectoPagarIntf.pas',
  dmi_rdp in '..\..\Interface\Gim10\dmi_rdp.pas',
  RemesaPagoIntf in '..\..\Interface\Gim10\RemesaPagoIntf.pas',
  dmi_rem in '..\..\Interface\Gim10\dmi_rem.pas',
  RemesaIntf in '..\..\Interface\Gim10\RemesaIntf.pas',
  dm_ecc in '..\Gdm10\dm_ecc.pas' {EfectoCobrarModule: TDataModule},
  QueryForm in '..\..\Lib\QueryForm.pas' {FilterFrame: TFrame},
  SessionIntf in '..\..\Interface\Lib\SessionIntf.pas',
  dm_ccf in '..\Gdm70\dm_ccf.pas' {CierreCicloFabricacionModule: TDataModule},
  dmi_ccn in '..\..\Interface\Gim10\dmi_ccn.pas',
  dmi_rda in '..\..\Interface\Gim10\dmi_rda.pas',
  dmi_vec in '..\..\Interface\Gim10\dmi_vec.pas',
  dmi_gaa in '..\..\Interface\Gim10\dmi_gaa.pas',
  dmi_sds in '..\..\Interface\Gim10\dmi_sds.pas',
  dmi_cde in '..\..\Interface\Gim10\dmi_cde.pas',
  dm_fac in '..\Gdm10\dm_fac.pas' {FacturaModule},
  dm_ast in '..\Gdm10\dm_ast.pas' {AsientoModule: TDataModule},
  dmi_fac in '..\..\Interface\Gim10\dmi_fac.pas',
  LineaMovimientoIntf in '..\..\Interface\Gim30\LineaMovimientoIntf.pas',
  dmi_mov in '..\..\Interface\Gim30\dmi_mov.pas',
  MovimientoIntf in '..\..\Interface\Gim30\MovimientoIntf.pas',
  SessionDataAccess in '..\..\Lib\SessionDataAccess.pas' {SessionDataModule: TDataModule},
  EditSelector in '..\..\Lib\EditSelector.pas' {SelectorRelationForm},
  dmi_fdc in '..\..\Interface\Gim30\dmi_fdc.pas',
  dmi_rdr in '..\..\Interface\Gim30\dmi_rdr.pas',
  ParametrosFacturacionIntf in '..\..\Interface\Gim30\ParametrosFacturacionIntf.pas',
  dmi_fdv in '..\..\Interface\Gim30\dmi_fdv.pas',
  dm_ecp in '..\Gdm10\dm_ecp.pas' {EfectoPagarModule: TDataModule},
  b_lcl in '..\Gdm30\b_lcl.pas' {BoxLclForm},
  dm_rem in '..\Gdm10\dm_rem.pas' {RemesaModule: TDataModule},
  dm_rdp in '..\Gdm10\dm_rdp.pas' {RemesaPagoModule: TDataModule},
  dmi_sto in '..\..\Interface\Gim30\dmi_sto.pas',
  dmi_ric in '..\..\Interface\Gim10\dmi_ric.pas',
  FacturaVentasIntf in '..\..\Interface\Gim30\FacturaVentasIntf.pas',
  dmi_vpe in '..\..\Interface\Gim30\dmi_vpe.pas',
  Gim90Fields in '..\..\Interface\Gim90\Gim90Fields.pas',
  a_cat in '..\Gdm207\a_cat.pas' {MntCatForm: TgForm},
  cx_cat in '..\Gdm207\cx_cat.pas' {CxCatForm: TgForm},
  dm_rea207 in '..\Gdm207\dm_rea207.pas' {RegistroActualizacionTiendaModule: TDataModule},
  gdm207Dm in '..\Gdm207\gdm207Dm.pas' {DataModule207: TDataModule},
  l_cat in '..\Gdm207\l_cat.pas' {RptCatForm: TgForm},
  a_pde207 in '..\Gdm207\a_pde207.pas' {MntPde207Form: TgForm},
  f_cnf207 in '..\Gdm207\f_cnf207.pas' {Configuracion207Module: TDataModule},
  Gim207Fields in '..\..\Interface\Gim207\Gim207Fields.pas',
  dm_cat in '..\Gdm207\dm_cat.pas' {CategoriaModule: TDataModule},
  dmi_sdt in '..\..\Interface\Gim207\dmi_sdt.pas',
  dmi_lma in '..\..\Interface\Gim30\dmi_lma.pas',
  dmi_cec in '..\..\Interface\Gim30\dmi_cec.pas',
  dmi_iav101 in '..\..\Interface\Gim101\dmi_iav101.pas',
  Gim101Fields in '..\..\Interface\Gim101\Gim101Fields.pas',
  gdm101Frm in '..\Gdm101\gdm101Frm.pas' {Gds101Frm: TFrame},
  a_pg101 in '..\Gdm101\a_pg101.pas' {mntPg101Form: TgForm},
  b_iav101 in '..\Gdm101\b_iav101.pas' {BoxIav101Form: TgForm},
  dm_iav103 in '..\Gdm103\dm_iav103.pas' {ImportacionAlbaranesVenta103Module: TDataModule},
  Gim203Fields in '..\..\Interface\Gim203\Gim203Fields.pas',
  Gim204Fields in '..\..\Interface\Gim204\Gim204Fields.pas',
  dmi_iav103 in '..\..\Interface\Gim103\dmi_iav103.pas',
  dm_iav101 in '..\Gdm101\dm_iav101.pas' {ImportacionAlbaranesVenta101Module: TDataModule},
  dmi_hdc in '..\..\Interface\Gim40\dmi_hdc.pas',
  HojaCargaIntf in '..\..\Interface\Gim40\HojaCargaIntf.pas',
  LineaHojaCargaIntf in '..\..\Interface\Gim40\LineaHojaCargaIntf.pas',
  b_iav103 in '..\Gdm103\b_iav103.pas' {BoxIav103Form: TgForm},
  b_ifv117 in '..\Gdm117\b_ifv117.pas' {BoxIfv117Form: TgForm},
  dmi_ifv117 in '..\..\Interface\Gim117\dmi_ifv117.pas',
  b_nda in '..\Gdm40\b_nda.pas' {BoxNdaForm: TgForm},
  f_fco in '..\Gdm200\f_fco.pas' {FcoFrame: TFrame},
  dmi_art in '..\..\Interface\Gim30\dmi_art.pas',
  ClienteIntf in '..\..\Interface\Gim10\ClienteIntf.pas',
  NexusRpcData in '..\..\Lib\NexusRpcData.pas' {NexusRpcDataModule: TDataModule},
  PDFViewer in '..\..\Lib\PDFViewer.pas' {PDFViewerForm: TgForm},
  i_rdr in '..\Gdm10\i_rdr.pas' {RptRdrForm: TgForm},
  Gdm70Dm in '..\Gdm70\Gdm70Dm.pas' {DataModule70: TDataModule},
  dmi_sen in '..\..\Interface\Gim203\dmi_sen.pas',
  Gim70Fields in '..\..\Interface\Gim70\Gim70Fields.pas',
  l_tcm in '..\Gdm201\l_tcm.pas' {RptTcmForm: TgForm},
  dmi_iva in '..\..\Interface\Gim10\dmi_iva.pas',
  dm_cdc in '..\Gdm70\dm_cdc.pas' {CodigoCosteModule: TDataModule},
  dmi_odf in '..\..\Interface\Gim70\dmi_odf.pas',
  b_lan in '..\Gdm70\b_lan.pas' {BoxLanForm: TgForm},
  dm_odf in '..\Gdm70\dm_odf.pas' {OrdenFabricacionModule: TDataModule},
  f_cnf70 in '..\Gdm70\f_cnf70.pas' {ProduccionModule: TDataModule},
  a_pde7 in '..\Gdm70\a_pde7.pas' {MntPde7Form: TgForm},
  a_cer in '..\Gdm00\a_cer.pas' {MntCerForm: TgForm},
  f_cnf208 in '..\Gdm208\f_cnf208.pas' {SuministroInformacionModule: TDataModule},
  OrdenFabricacionIntf in '..\..\Interface\Gim70\OrdenFabricacionIntf.pas',
  dmi_cla in '..\..\Interface\Gim70\dmi_cla.pas',
  dmi_lmp in '..\..\Interface\Gim70\dmi_lmp.pas',
  dmi_cpr in '..\..\Interface\Gim70\dmi_cpr.pas',
  dmi_maq in '..\..\Interface\Gim70\dmi_maq.pas',
  dmi_idf in '..\..\Interface\Gim70\dmi_idf.pas',
  InformeFabricacionIntf in '..\..\Interface\Gim70\InformeFabricacionIntf.pas',
  gdm10Dm in '..\Gdm10\gdm10Dm.pas' {DataModule10: TDataModule},
  FacturaComprasIntf in '..\..\Interface\Gim30\FacturaComprasIntf.pas',
  dm_cri116 in '..\Gdm116\dm_cri116.pas' {Cristaleria116Module: TDataModule},
  b_ccf in '..\Gdm70\b_ccf.pas' {BoxCcfForm: TgForm},
  dmi_ccf in '..\..\Interface\Gim70\dmi_ccf.pas',
  dmi_rdip in '..\..\Interface\Gim70\dmi_rdip.pas',
  b_tbf in '..\Gdm205\b_tbf.pas' {TabletaFirmaForm: TgForm},
  dm_tbf in '..\Gdm205\dm_tbf.pas' {TabletaFirmaDataModule: TDataModule},
  wgssSTU_TLB in '..\Gdm205\wgssSTU_TLB.pas',
  b_rra in '..\Gdm207\b_rra.pas' {BoxRraForm: TgForm},
  dmi_cfg105 in '..\..\Interface\Gim105\dmi_cfg105.pas',
  dm_bei in '..\Gdm10\dm_bei.pas' {BalancesInformesModule: TDataModule},
  b_blp in '..\Gdm10\b_blp.pas' {BoxBlpForm: TgForm},
  Gim114Fields in '..\..\Interface\Gim114\Gim114Fields.pas',
  dmi_cnd in '..\..\Interface\Gim00\dmi_cnd.pas',
  dmi_dcm114 in '..\..\Interface\Gim114\dmi_dcm114.pas',
  a_fcg in '..\Gdm10\a_fcg.pas' {MntFcgForm: TgForm},
  a_fvi in '..\Gdm10\a_fvi.pas' {MntFviForm: TgForm},
  dm_rpf in '..\Gdm10\dm_rpf.pas' {RegistroPresentacionModule: TDataModule},
  dm_sfe in '..\Gdm10\dm_sfe.pas' {SFEmitidasModule: TDataModule},
  dm_sfr in '..\Gdm10\dm_sfr.pas' {SFRecibidasModule: TDataModule},
  SuministroFactEmitidas in '..\Gdm10\SuministroFactEmitidas.pas',
  SuministroFactRecibidas in '..\Gdm10\SuministroFactRecibidas.pas',
  b_sfa in '..\Gdm208\b_sfa.pas' {BoxSfaForm: TgForm},
  dmi_nda in '..\..\Interface\Gim40\dmi_nda.pas',
  gdm40Frm in '..\Gdm40\gdm40Frm.pas' {gds40Frm: TFrame},
  AppForms in '..\..\Lib\AppForms.pas' {ApplicationForms: TFrame},
  dm_nda in '..\Gdm40\dm_nda.pas' {AprovisionamientoModule: TDataModule},
  dm_idf in '..\Gdm70\dm_idf.pas' {InformeFabricacionModule: TDataModule},
  b_rof in '..\Gdm70\b_rof.pas' {BoxRofForm: TgForm},
  b_sdt207 in '..\Gdm207\b_sdt207.pas' {BoxSdt207Form: TgForm},
  dm_sdt207 in '..\Gdm207\dm_sdt207.pas' {SincronizacionTiendaMagentoModule: TDataModule},
  dm_tvr in '..\Gdm207\dm_tvr.pas' {TiendaVirtualModule: TDataModule},
  dmi_pve in '..\..\Interface\Gim30\dmi_pve.pas',
  GridTableViewController in '..\..\Lib\GridTableViewController.pas',
  QueryGrid in '..\..\Lib\QueryGrid.pas' {QueryGridFrame: TFrame},
  dm_rdc118 in '..\Gdm118\dm_rdc118.pas' {FerroDataModule: TDataModule},
  b_test207 in '..\Gdm207\b_test207.pas' {BoxTest207Form: TgForm},
  b_odf_1 in '..\Gdm70\b_odf_1.pas' {BoxOdf1Frame: TFrame},
  dm_sst119 in '..\Gdm119\dm_sst119.pas' {SuministroStocksModule: TDataModule},
  b_cds119 in '..\Gdm119\b_cds119.pas' {BoxCds119Form: TgForm},
  a_pde_con in '..\Gdm10\a_pde_con.pas' {BoxPdeConForm: TgForm},
  a_pde_art in '..\Gdm30\a_pde_art.pas' {BoxPdeArtForm: TgForm},
  a_pde_cli in '..\Gdm30\a_pde_cli.pas' {BoxPdeCliForm: TgForm},
  a_pde_pro in '..\Gdm30\a_pde_pro.pas' {BoxPdeProForm: TgForm},
  a_pde_com in '..\Gdm30\a_pde_com.pas' {BoxPdeComForm: TgForm},
  a_pde_ven in '..\Gdm30\a_pde_ven.pas' {BoxPdeVenForm: TgForm},
  a_pde_alm in '..\Gdm30\a_pde_alm.pas' {BoxPdeAlmForm: TgForm},
  dm_sdp119 in '..\Gdm119\dm_sdp119.pas' {SuministroPedidosModule: TDataModule},
  b_rea119 in '..\Gdm119\b_rea119.pas' {mntRea119Form: TgForm},
  a_pde119 in '..\Gdm119\a_pde119.pas' {MntPde119Form: TgForm},
  b_pst119 in '..\Gdm119\b_pst119.pas' {BoxPst119Form: TgForm},
  Gim60Fields in '..\..\Interface\Gim60\Gim60Fields.pas',
  gdm119Dm in '..\Gdm119\gdm119Dm.pas' {DataModule119: TDataModule},
  Gim119Fields in '..\..\Interface\Gim119\Gim119Fields.pas',
  b_atf in '..\Gdm70\b_atf.pas' {BoxAtfForm: TgForm},
  gdm20Frm in '..\Gdm20\gdm20Frm.pas' {Gds20Frm: TFrame},
  Gdm20Dm in '..\Gdm20\Gdm20Dm.pas' {DataModule20: TDataModule},
  b_2fa in '..\Gdm207\b_2fa.pas' {Box2faForm: TgForm},
  dm_pga in '..\Gdm00\dm_pga.pas' {ConfiguracionModule: TDataModule},
  ComPort in '..\..\Lib\ComPort.pas',
  l_bei in '..\Gdm10\l_bei.pas' {RptBeiForm: TgForm},
  dm_ifv117 in '..\Gdm117\dm_ifv117.pas' {ImportacionFacturasVenta117Module: TDataModule},
  dm_hpd120 in '..\Gdm120\dm_hpd120.pas' {HojasDePedido120Module: TDataModule},
  l_shp in '..\Gdm120\l_shp.pas' {RptShpForm: TgForm},
  AppForm in '..\GdLib\AppForm.pas' {ApplicationForm: TgxForm},
  AppContainer in '..\..\Lib\AppContainer.pas' {ApplicationContainer: TFrame},
  b_roi in '..\Gdm204\b_roi.pas' {BoxRolForm: TgxForm},
  bx_not in '..\..\Lib\bx_not.pas' {BoxNotForm: TgxForm},
  dm_cfg105 in '..\Gdm105\dm_cfg105.pas' {Configuracion105Module: TDataModule},
  f_cpv105 in '..\Gdm105\f_cpv105.pas' {CpvFrame: TFrame},
  f_fpv105 in '..\Gdm105\f_fpv105.pas' {FpvFrame: TFrame},
  f_lcv105 in '..\Gdm105\f_lcv105.pas' {RptLcv105Module: TDataModule},
  f_lma105 in '..\Gdm105\f_lma105.pas' {ListaMateriales105Module: TDataModule},
  gdm105Dm in '..\Gdm105\gdm105Dm.pas' {DataModule105: TDataModule},
  f_sfv in '..\Gdm30\f_sfv.pas' {SfvFrame: TFrame},
  f_cdt116 in '..\Gdm116\f_cdt116.pas' {CdtFrame: TFrame},
  dmi_cri116 in '..\..\Interface\Gim116\dmi_cri116.pas',
  gdm116Dm in '..\Gdm116\gdm116Dm.pas' {DataModule116: TDataModule},
  Gim116Fields in '..\..\Interface\Gim116\Gim116Fields.pas',
  Gim103Fields in '..\..\Interface\Gim103\Gim103Fields.pas',
  b_vmc in '..\Gdm116\b_vmc.pas' {BoxVmcForm: TgxForm},
  b_rrc in '..\Gdm30\b_rrc.pas' {BoxRrcForm: TgxForm},
  Gim105Fields in '..\..\Interface\Gim105\Gim105Fields.pas',
  b_ddb in '..\Gdm105\b_ddb.pas' {BoxDdbForm: TgxForm},
  f_dsb_cbl in '..\Gdm00\f_dsb_cbl.pas' {DashboardChartBarLineFrame: TFrame},
  f_dsb_cdo in '..\Gdm00\f_dsb_cdo.pas' {DashboardChartDonutFrame: TFrame},
  f_dsb_prb in '..\Gdm00\f_dsb_prb.pas' {DashboardProgressLineFrame: TFrame},
  p_con in '..\Gdm10\p_con.pas' {GestionContableFrame: TDashBoardSectionFrame},
  b_rfe in '..\Gdm200\b_rfe.pas' {BoxRfeForm: TgxForm},
  b_ife in '..\Gdm200\b_ife.pas' {BoxIfeForm: TgxForm

{$R *.RES},
  FacturaIntf in '..\..\Interface\Gim10\FacturaIntf.pas',
  dmi_pga in '..\..\Interface\Gim00\dmi_pga.pas',
  dm_fce in '..\Gdm200\dm_fce.pas' {FacturaElectronicaDataModule: TDataModule},
  dmi_iex in '..\..\Interface\Gim00\dmi_iex.pas',
  dm_ptv in '..\Gdm207\dm_ptv.pas' {ParametrosTiendaVirtualModule: TDataModule},
  cm_mdc in '..\Gdm30\cm_mdc.pas' {CmdMdcModule: TDataModule},
  cm_mve40 in '..\Gdm40\cm_mve40.pas' {CmdMve40Module: TDataModule},
  b_ifv121 in '..\Gdm121\b_ifv121.pas' {BoxIfv121Form: TgxForm},
  dm_ifv121 in '..\Gdm121\dm_ifv121.pas' {ImportacionFacturas121Module: TDataModule},
  dmi_ifv121 in '..\..\Interface\Gim121\dmi_ifv121.pas',
  ReportManager in '..\..\Lib\Custom\FastReport\Source\ReportManager.pas' {ReportManagerDataModule: TDataModule},
  f_not in '..\..\Lib\Custom\FastReport\Source\f_not.pas' {AnnotationFrame: TFrame},
  dmi_rpf in '..\..\Interface\Gim10\dmi_rpf.pas';

{$R *.RES}

// Estas opciones hacen que se cargue toda la aplicación en memoria y evita que se lean páginas desde el servidor cuando se necesitan (entre otras cosas)

const  IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = $8000;

{$SetPEOptFlags IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE}
{$SetPEFlags IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP or IMAGE_FILE_NET_RUN_FROM_SWAP}

procedure DoOnStart;
begin
     // ReportManagerDataModule.DesignReport;
end;

begin

     // ReportMemoryLeaksOnShutdown := True;

     // NeverSleepOnMMThreadContention := True;

     Application.Initialize;

     Application.Title := 'Gestwin 11';

     // ReportEditor := True;
     Application.CreateForm(TApplicationForm, ApplicationForm);
  ApplicationContainer.UserCanModifyReports := True;

     ShowQueryWithEditor := True;
     ProgramNumber := 3;
     Sp64BitsServer := True;

     Application.MainFormOnTaskbar := True;
     Application.Run;
end.


