ScroogeXHTML for Delphi: TXHTML10TransitionalTranslator Class Reference
TXHTML10TransitionalTranslator Class Reference
XHTML 1.0 Transitional Translator.
Public Member Functions
string GetDocType ()
string GetDocTypeName ()
string GetParagraphStyle (const TParagraphProperties PP)
Returns the HTML for a P element (paragraph).
Boolean IsTransitional ()
Public Member Functions inherited from TXHTMLTranslator
string GetRootElement ()
Returns the document root element.
string GetCloseEmptyElement ()
Returns " />".
SxText FormatElement (const SxText Text, const TCharacterProperties CP)
Returns text with formatting CSS/XHTML tags.
Boolean IsXml ()
Returns True because all subclasses are XML based.
Public Member Functions inherited from TCustomTranslator
string BuildLangAttribute (const string Language)
Returns lang attribute.
string IndentCrLf ()
Returns carriage return / line feed and margin.
string GetFontSizeStyle (const Integer Pt)
Returns a CSS style for the given font size.
string GetMargin ()
Returns a sequence of spaces (the left margin).
SXText Encode (const SXText S)
Encode Unicode string using UTF-8.
string GetRootElement ()
Returns the HTML / XHTML document root element.
string GetCloseEmptyElement ()
Returns the correct closing bracket for an empty element.
SxText FormatElement (const SxText Text, const TCharacterProperties CP)
Returns text with formatting CSS/HTML/XHTML tags.
string GetDocType ()
Get the DOCTYPE definition.
string GetDocTypeName ()
Get the name of the doctype.
string GetParagraph (const string AdditionalStyle, const string AdditionalParams= '')
returns the start tag for a paragraph element
string GetParagraphStyle (const TParagraphProperties PP)
Converts the paragraph properties to a style definition.
SetParOpen (const string TagAndClass, const string DefaultStyle)
Setter for the 'paragraph open' tag.
string GetStyleParam (const string AdditionalStyle)
Get style parameter.
Boolean SupportsElement (const string ElementName)
Returns True if the element is supported by the current doctype.
Boolean SupportsParameter (const string ElementName, const string ParamName)
Returns True if the element supports the given parameter.
string GetIndentAndDirectionStyle (const TParagraphProperties PP)
Returns a indent and direction style for the paragraph.
SxText GetCharacterStyles (const SxText Text, const TCharacterProperties CP)
Returns text with styles applied for the given character properties.
boolean IsTransitional ()
Returns True if the document type is a transitional version.
Boolean IsDocTypeRequired ()
Returns True if a DOCTYPE declaration is required (see XHTML 1.1).
Boolean IsXml ()
Returns True if it is an XML based Translator.
SetFontSizeScale (const TFontSizeScale FSS)
Setter for the font size scale.
Detailed Description
XHTML 1.0 Transitional Translator.
Member Function Documentation
string TXHTML10TransitionalTranslator::GetParagraphStyle (const TParagraphProperties PP)
Returns the HTML for a P element (paragraph).
Note
XHTML 1.0 Transitional supports the 'classic' HTML parameter align="..." for left or right aligned and centered paragraphs for the P element (see: xhtml1-transitional.dtd). To be backward compatible with older HTML browsers, this parameter will be used where possible. For justified paragraphs, a CSS style parameter will be used.
References TXHTMLTranslator::FormatElement(), TCustomTranslator::GetIndentAndDirectionStyle(), TCustomTranslator::GetParagraph(), TXHTMLTranslator::GetRootElement(), TCustomTranslator::IsDocTypeRequired(), TCustomTranslator::SupportsElement(), and TCustomTranslator::SupportsParameter().