ScroogeXHTML for Delphi: TCustomScrooge Class Reference
TCustomScrooge Class Reference
Main ScroogeXHTML component unit.
Public Member Functions
ConvertRTFFile (const TFileName RTFFilename, const TFileName HTMLFilename)
Convert a RTF file to a HTML file.
UTF8String ConvertRTF (const TFileName RTFfilename)
Convert a RTF file to a HTML string.
UTF8String RichEditToHTML (const TRichedit Source)
Convert the RichEdit RTF code to HTML/XHTML.
Public Member Functions inherited from TSxMain
UTF8String Convert (const RawByteString RTF)
Convert RTF to HTML / XHTML.
string GetLeadingHTMLTags ()
Build the tags before the HTML body code.
string GetTrailingHTMLTags ()
Build the tags after the HTML body code.
Public Member Functions inherited from TSxBase
TSxBase (TComponent AOwner)
create a new TSxBase instance
~TSxBase ()
Destroy TSxBase instance.
VerifySettings ()
Checks properties for invalid settings.
string GetCloseEmptyElement ()
check if we are in debug mode
string GetEmptyParagraph ()
returns an empty paragraph
string GetParOpen ()
returns the opening tag for a paragraph without "&gt;"
string GetOrderedListTag ()
get the opening tag for an ordered list
string GetUnorderedListTag ()
get the opening tag for an unordered list
string GetElementClassParam (const string ElementName)
returns the class parameter for the given element
string GetElementStyleParam (const string ElementName)
returns the style="..." parameter for the given element
string GetElementStyle (const string ElementName)
returns the CSS style for the given element
string GetLineBreakTag ()
returns the line break element
Log (const TLogLevel alogLevel, const SXText logText)
call the log event handler and pass the log level and message
ReplaceFont (string &FontName)
replace a font name
ReplaceHyperlink (const ISimpleDomTextNode TextElement)
replace a hyperlink
SxText TextElementToXHTML (const ISimpleDomTextNode TextElement)
convert a text element to HTML / XHTML.
Additional Inherited Members
Public Attributes inherited from TSxBase
Boolean AbortConversion
set this property to True to abort the conversion
ISxFormatter Formatter
The formatter.
IPictureAdapter PictureAdapter
The picture adapter.
Boolean RtfEnd
True -> end of document or conversion aborted.
ISxTranslator Translator
The HTML / XHTML Translator.
Boolean ConvertEmptyParagraphs
Set this property to True to replace empty paragraphs (where the opening <p> tag is followed by the closing </p> tag) by a line break tag (<br />).
Boolean ConvertHyperlinks
Set this property to True to activate hyperlink support.
Boolean ConvertIndent
Set this property to True if You want to activate support for left and right paragraph indent.
Boolean ConvertLanguage
Activates support for language conversion.
Boolean ConvertPictures
Activates support for picture conversion.
Boolean ConvertSpaces
If two or more spaces are found in sequence, they will be converted to &nbsp;.
Boolean ConvertToPlainText
Convert to plain text.
Boolean ConvertUsingPrettyIndents
ScroogeXHTML generates output documents with 'pretty printed' formatting by default.
Boolean DebugMode
In debug mode, the HTML code includes all elements of the RTF document (RTF tokens, control characters...).
string DefaultLanguage
Use this property to set the default language of the document.
TDocumentType DocumentType
The document type.
TStrings ElementClasses
A list of name-value pairs which defines the class="..." parameter for the elements 'p', 'br', 'ol', 'ul' and 'li'.
TStrings ElementStyles
A list of name-value pairs which defines the style="..." parameter for the elements 'p', 'br', 'ol', 'ul' and 'li'.
TFontConversionOptions FontConversionOptions
Set these options to control which character properties are converted.
TFontSizeScale FontSizeScale
Use this option to set the font size scale.
TStrings HyperlinkList
In this list of name value pairs, the visible link text for all known target addresses is associated with an URL.
THyperlinkOptions HyperlinkOptions
This property controls additional options for the hyperlink conversion.
Boolean IncludeDocType
Include DOCTYPE at the beginning of the document.
Boolean IncludeXMLDeclaration
Includes the XML declaration line at the beginning of the document.
TLogLevel LogLevel
This property can be used to control the detail level of the logging procedure.
TStrings ReplaceFonts
Font names which will be replaced.
string TabString
the HTML representation of a TAB charcter
string Version
the ScroogeXHTML version
TSxOptionsHead OptionsHead
TSxOptionsOptimize OptionsOptimize
TNotifyEvent OnAfterConvert
This event handler will be called after the conversion.
TEncodingEvent OnAfterEncode
Event handler which will be called after the encoding.
TNotifyEvent OnBeforeConvert
Event handler which will be called before the conversion.
TEncodingEvent OnBeforeEncode
Event handler which will be called before the encoding.
THyperlinkEvent OnHyperlink
This event handler will be called if a hyperlink is detected.
TLogEvent OnLog
Event handler for log messages.
TProgressEvent OnProgress
This event is called periodically during the conversion.
TReplaceFontEvent OnReplaceFont
This event handler can be used to define a font substition.
Detailed Description
Main ScroogeXHTML component unit.
This class implements the high-level converter methods ConvertRTFFile and RichEditToHTML. The third conversion method, TSxBase::Convert, is defined in the superclass.
Member Function Documentation
UTF8String TCustomScrooge::ConvertRTF (const TFileName RTFfilename)
Convert a RTF file to a HTML string.
RTFFilename The name of the input RTF file
References TSxMain::Convert().
Referenced by ConvertRTFFile().
TCustomScrooge::ConvertRTFFile (const TFileName RTFFilename, const TFileName HTMLFilename)
Convert a RTF file to a HTML file.
To write an application which can convert a RTF file to a HTML/XHTML file,
drop a ScroogeXHTML component on the form
add a button to the form and enter the following code for the OnClick event:
var
 RTFFile, XHTMLFile: string;
begin
  RTFFile := 'c:\windows\desktop\test.rtf';
  XHTMLFile := 'c:\windows\desktop\test.html';
  ScroogeXHTML1.ConvertRTFFile(RTFFile, XHTMLFile);
end;
RTFFilename The name of the input RTF file
HTMLFilename The name of the output HTML/XHTML file
References ConvertRTF().
UTF8String TCustomScrooge::RichEditToHTML (const TRichedit Source)
Convert the RichEdit RTF code to HTML/XHTML.
Source The TRichEdit control instance.
References TSxMain::Convert().