{##############################################################################}
{# NexusDB: nxemDefine.inc 4.70                                               #}
{# Copyright (c) Nexus Database 2003-2023                                     #}
{# All rights reserved.                                                       #}
{##############################################################################}
{# NexusDB: Enterprise Manager Compiler options/directives include file       #}
{##############################################################################}

{$I nxDefine.inc}

(**** activate this to compile FastReport report engine into EM ****)

{$DEFINE EMIncludeReportEngine}

(**** activate this to compile Active Query Builder into EM ****)

{.$DEFINE EMIncludeActiveQueryBuilder}

